language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.3
      env: DJANGO=1.10
    - python: 3.3
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=1.8
    - python: 3.6
      env: DJANGO=1.9
    - python: 3.6
      env: DJANGO=1.10

install:
  - pip install Django==$DJANGO
  - pip install coveralls coverage
  - python setup.py -q install

script:
  - coverage run --source=django_tinsel test_app/manage.py test django_tinsel_tests

after_success:
  - coveralls --verbose
