language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11

matrix:
  exclude:
    - python: 3.6
      env: DJANGO=1.8
    - python: 3.6
      env: DJANGO=1.9
    - python: 3.6
      env: DJANGO=1.10
    - python: 3.7
      env: DJANGO=1.8
    - python: 3.7
      env: DJANGO=1.9
    - python: 3.7
      env: DJANGO=1.10
    - python: 3.8
      env: DJANGO=1.8
    - python: 3.8
      env: DJANGO=1.9
    - python: 3.8
      env: DJANGO=1.10

install:
  - pip install Django==$DJANGO
  - pip install coveralls coverage
  - python setup.py -q install

script:
  - coverage run --source=django_tinsel test_app/manage.py test django_tinsel_tests

deploy:
  provider: pypi
  user: azavea
  password:
    secure: A+EnXPAjeSIQKra9euWmfCPniF1QebTJKJKqZxbCc1u/r2PBBxCD8duWakcKCTfMy7Fdwex1Ms5lk9gGxz+C29ZWffYqAbhQGByR/dhkmIlfi7PdBrofCm5VMf53MgW+54M5zKXuEreGxfTMNQ29w2x45fwehTCiS43rA3gaf/8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: azavea/django-tinsel

after_success:
  - coveralls --verbose
